package com.entity;
// Generated 2018-6-30 11:56:40 by Hibernate Tools 4.3.1.Final

/**
 * LookInfo generated by hbm2java
 */
public class lookInfo implements java.io.Serializable {

	private int infoId;
	private String gameName;
	private String lookerName;
	private String adName;
	private String lookTime;

	public lookInfo() {
	}

	public lookInfo(int infoId) {
		this.infoId = infoId;
	}

	public lookInfo(int infoId, String gameName, String lookerName, String adName, String lookTime) {
		this.infoId = infoId;
		this.gameName = gameName;
		this.lookerName = lookerName;
		this.adName = adName;
		this.lookTime = lookTime;
	}

	public int getInfoId() {
		return this.infoId;
	}

	public void setInfoId(int infoId) {
		this.infoId = infoId;
	}

	public String getGameName() {
		return this.gameName;
	}

	public void setGameName(String gameName) {
		this.gameName = gameName;
	}

	public String getLookerName() {
		return this.lookerName;
	}

	public void setLookerName(String lookerName) {
		this.lookerName = lookerName;
	}

	public String getAdName() {
		return this.adName;
	}

	public void setAdName(String adName) {
		this.adName = adName;
	}

	public String getLookTime() {
		return this.lookTime;
	}

	public void setLookTime(String lookTime) {
		this.lookTime = lookTime;
	}

	@Override
	public String toString() {
		return "lookInfo [infoId=" + infoId + ", gameName=" + gameName + ", lookerName=" + lookerName + ", adName="
				+ adName + ", lookTime=" + lookTime + "]";
	}

	
	
}
